join-quit-message:
  enabled: true
  join-message: "&f[&a+&f] %player_name%"
  leave-message: "&f[&4-&f] %player_name%"

chat-message:
  enabled: true
  player-chat: "%vault_prefix% %player_name% > %message%"

gm-message: "%player_name% Votre gamemode a bien été changé"
fly-enable: "Vous avez été désactivé de fly."
fly-disable: "Vous avez été activé pour fly."

worlds:
  - world
  - world_nether
  - world_the_end