name: foxlobby
version: 1.0.0
author: achul123
main: io.achul123.Main
commands:
  gm:
    description: alliase de gamemode
    permission: fp.gm

permissions:
  gm:
    description: Allows you to use /gm
    default: op